@startuml
package UNEATLANTICO{

    class Titulacion{
        curso
    }

    class Departamento{
        jefeDepartamento

    }

    class Profesor{
        titulación
        categoría
        ECTS
    }

    Enum Contrato{
    }

    Enum Experiencia

    class Asignatura{

        semestre
        codigoCampus
        tipo
        ECTS
    }

    class PlanEstudios{
    }

    class MemoriaAcademica{
        año
    }

    class CargaAcademica{
        curso
    }
}

Profesor --> Departamento
Profesor -d-> CargaAcademica
CargaAcademica -d-> Asignatura
PlanEstudios -l-> Asignatura
Departamento -> Asignatura
Titulacion -d-> PlanEstudios
Asignatura -d-> MemoriaAcademica

Profesor .. Titulacion
Profesor -l- Contrato
Profesor -r- Experiencia


@enduml